#!/usr/bin/env python3
"""Generate a zero-paid-infrastructure local cron deployment for a configured Savings bundle."""
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CRON_TOKEN = re.compile(r"^[0-9*/,-]+$")


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def validate_cron(value: str) -> str:
    parts = value.strip().split()
    if len(parts) != 5:
        raise ValueError("schedule must be a five-field cron expression")
    if not all(CRON_TOKEN.fullmatch(part) for part in parts):
        raise ValueError("schedule contains unsupported/unsafe cron token")
    return " ".join(parts)


def deployment_plan(bundle: Path) -> dict:
    installation = read_json(bundle / "installation.json")
    config = read_json(bundle / "config.json")
    if installation.get("state") not in {"CLIENT_CONFIGURED", "CLIENT_ACCEPTED"}:
        raise ValueError("local live deployment requires CLIENT_CONFIGURED or CLIENT_ACCEPTED")
    schedule = config.get("schedule")
    return {
        "tenantId": installation["tenantId"],
        "installationId": installation["installationId"],
        "workflowKey": installation["workflowKey"],
        "workflowVersion": installation["workflowVersion"],
        "state": installation["state"],
        "schedule": validate_cron(schedule) if schedule else None,
        "mode": "scheduled" if schedule else "event",
        "dedicatedInfrastructure": installation.get("dedicatedInfrastructure", False),
    }


def build_live_command(repo_root: Path, bundle: Path, node: str) -> str:
    runner = repo_root / "operations/savings/runtime/run_live.mjs"
    return " ".join([
        shlex.quote(node),
        shlex.quote(str(runner)),
        "--bundle",
        shlex.quote(str(bundle)),
        "--confirm-live-side-effects",
        "YES",
    ])


def generate_cron(
    bundle: Path,
    out: Path,
    *,
    repo_root: Path = ROOT,
    node: str = "node",
    env_file: Path | None = None,
) -> dict:
    plan = deployment_plan(bundle)
    if not plan["schedule"]:
        raise ValueError("bundle has no schedule; use event-spool execution for this workflow")

    out.mkdir(parents=True, exist_ok=True)
    state_dir = bundle / "runtime-state"
    log_path = state_dir / "scheduler.log"
    wrapper = out / "run.sh"
    cron_file = out / "crontab.txt"

    lines = [
        "#!/bin/sh",
        "set -eu",
        "umask 077",
    ]
    if env_file:
        lines += [
            f"ENV_FILE={shlex.quote(str(env_file))}",
            'if [ ! -f "$ENV_FILE" ]; then echo "missing credential env file: $ENV_FILE" >&2; exit 2; fi',
            "set -a",
            '. "$ENV_FILE"',
            "set +a",
        ]
    lines += [
        f"cd {shlex.quote(str(repo_root))}",
        f"exec {build_live_command(repo_root, bundle, node)}",
        "",
    ]
    wrapper.write_text("\n".join(lines), encoding="utf-8")
    os.chmod(wrapper, 0o700)

    cron_line = (
        f"{plan['schedule']} {shlex.quote(str(wrapper))} "
        f">> {shlex.quote(str(log_path))} 2>&1"
    )
    cron_file.write_text(
        "# Generated by tools/savings/deploy_local.py\n"
        "# Install deliberately with: crontab <path-to-this-file>\n"
        f"{cron_line}\n",
        encoding="utf-8",
    )

    result = {
        **plan,
        "deploymentMode": "LOCAL_CRON",
        "wrapper": str(wrapper),
        "crontab": str(cron_file),
        "log": str(log_path),
        "envFile": str(env_file) if env_file else None,
        "secretMaterialWritten": False,
        "paidInfrastructureProvisioned": False,
    }
    (out / "deployment.json").write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    return result


def parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="command", required=True)

    plan = sub.add_parser("plan")
    plan.add_argument("--bundle", type=Path, required=True)
    plan.add_argument("--json", action="store_true")

    gen = sub.add_parser("generate-cron")
    gen.add_argument("--bundle", type=Path, required=True)
    gen.add_argument("--out", type=Path)
    gen.add_argument("--repo-root", type=Path, default=ROOT)
    gen.add_argument("--node", default="node")
    gen.add_argument("--env-file", type=Path)

    return ap


def main() -> int:
    args = parser().parse_args()
    try:
        if args.command == "plan":
            result = deployment_plan(args.bundle.resolve())
            print(json.dumps(result, indent=2) if args.json else (
                f"{result['workflowKey']} mode={result['mode']} schedule={result['schedule'] or '-'}"
            ))
            return 0

        if args.command == "generate-cron":
            bundle = args.bundle.resolve()
            out = (args.out or (bundle / "deployment/local-cron")).resolve()
            result = generate_cron(
                bundle,
                out,
                repo_root=args.repo_root.resolve(),
                node=args.node,
                env_file=args.env_file.resolve() if args.env_file else None,
            )
            print(json.dumps(result, indent=2))
            return 0

    except (ValueError, FileNotFoundError, json.JSONDecodeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    return 1


if __name__ == "__main__":
    sys.exit(main())
